# Generated by Django 3.1.2 on 2020-10-25 16:24

from django.db import migrations
from salas.models import User


def generate_default_users(apps, schema_editor):
    user1 = User.objects.create_user(username='cesar',
                                     email='cesar@local.com',
                                     password='qwerty')
    user1.name = 'cesar'
    user1.save()
    user2 = User.objects.create_user(username='r2d2',
                                     email='juan@local.com',
                                     password='qwerty')
    user2.name = 'juan'
    user2.save()
    # The system Superuser
    admin = User.objects.create_superuser(username='admin', email='admin@local.com', password='admin')
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_default_users)
    ]