# Generated by Django 3.1.2 on 2020-10-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_auto_20201025_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'permissions': [('crear_sala', 'Puede crear salas'), ('editar_sala', 'Puede editar informacion de las salas'), ('eliminar_sala', 'Puede eliminar salas')]},
        ),
    ]
